# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  todoapi:
    image: todoapi
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5269:5269
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
